from enum import Enum


class SymbolFillingModeEnum(Enum):
    # https://www.mql5.com/en/docs/constants/environment_state/marketinfoconstants#enum_symbol_info_integer
    SYMBOL_FILLING_FOK = 1
    SYMBOL_FILLING_IOC = 2
    SYMBOL_FILLING_ALL = 3





class ReturnCodeTradeServer(Enum):
    # https://www.mql5.com/en/docs/constants/errorswarnings/enum_trade_return_codes
    TRADE_RETCODE_REQUOTE = 10004
    TRADE_RETCODE_REJECT = 10006
    TRADE_RETCODE_CANCEL = 10007
    TRADE_RETCODE_PLACED = 10008
    TRADE_RETCODE_DONE = 10009
    TRADE_RETCODE_DONE_PARTIAL = 10010
    TRADE_RETCODE_ERROR = 10011
    TRADE_RETCODE_TIMEOUT = 10012
    TRADE_RETCODE_INVALID = 10013
    TRADE_RETCODE_INVALID_VOLUME = 10014
    TRADE_RETCODE_INVALID_PRICE = 10015
    TRADE_RETCODE_INVALID_STOPS = 10016
    TRADE_RETCODE_TRADE_DISABLED = 10017
    TRADE_RETCODE_MARKET_CLOSED = 10018
    TRADE_RETCODE_NO_MONEY = 10019
    TRADE_RETCODE_PRICE_CHANGED = 10020
    TRADE_RETCODE_PRICE_OFF = 10021
    TRADE_RETCODE_INVALID_EXPIRATION = 10022
    TRADE_RETCODE_ORDER_CHANGED = 10023
    TRADE_RETCODE_TOO_MANY_REQUESTS = 10024
    TRADE_RETCODE_NO_CHANGES = 10025
    TRADE_RETCODE_SERVER_DISABLES_AT = 10026
    TRADE_RETCODE_CLIENT_DISABLES_AT = 10027
    TRADE_RETCODE_LOCKED = 10028
    TRADE_RETCODE_FROZEN = 10029
    TRADE_RETCODE_INVALID_FILL = 10030
    TRADE_RETCODE_CONNECTION = 10031
    TRADE_RETCODE_ONLY_REAL = 10032
    TRADE_RETCODE_LIMIT_ORDERS = 10033
    TRADE_RETCODE_LIMIT_VOLUME = 10034
    TRADE_RETCODE_INVALID_ORDER = 10035
    TRADE_RETCODE_POSITION_CLOSED = 10036
    TRADE_RETCODE_INVALID_CLOSE_VOLUME = 10038
    TRADE_RETCODE_CLOSE_ORDER_EXIST = 10039
    TRADE_RETCODE_LIMIT_POSITIONS = 10040
    TRADE_RETCODE_REJECT_CANCEL = 10041
    TRADE_RETCODE_LONG_ONLY = 10042
    TRADE_RETCODE_SHORT_ONLY = 10043
    TRADE_RETCODE_CLOSE_ONLY = 10044
    TRADE_RETCODE_FIFO_CLOSE = 10045
    TRADE_RETCODE_HEDGE_PROHIBITED = 10046

class Common:
    SUCCESS_REQUEST_COMMENTS = [
        "Request executed", "Request executed partially"]
    MAPPING_FILLING_MODE_SYBOL_TO_ORDER = {
        "SYMBOL_FILLING_FOK": ["ORDER_FILLING_FOK"],
        "SYMBOL_FILLING_IOC": ["ORDER_FILLING_IOC"],
        "SYMBOL_FILLING_ALL": ["ORDER_FILLING_FOK", "ORDER_FILLING_IOC"],
    }
    SEPRATOR_NUMBER_STRING = '33'
    # Define successful retcodes
    SUCCESSFUL_MT5_TRADE_RETCODE = {
        ReturnCodeTradeServer.TRADE_RETCODE_PLACED.value,
        ReturnCodeTradeServer.TRADE_RETCODE_DONE.value,
        ReturnCodeTradeServer.TRADE_RETCODE_DONE_PARTIAL.value
    }
    DEFAULT_STOP_LOSS = 0.0
    DEFAULT_TAKE_PROFIT = 0.0
